[develop]
script_dir=$base/lib/stretch_core

[install]
install_scripts=$base/lib/stretch_core

[options.entry_points]
console_scripts =
    stretch_driver = stretch_core.stretch_driver:main
    usb_cam = stretch_core.usb_cam:main
    remote_gamepad = stretch_core.remote_gamepad:main
    luxonis_camera_node = stretch_core.luxonis_camera_node:main
    camera_info_publisher = stretch_core.camera_info_publisher:main
    stretch_lidar_check = stretch_core.stretch_lidar_check:main
