lidar:
  - driver:
      use_gpu: false
      source_type: 1
      
      # ALL network settings MUST go inside this block now
      lidar_udp_type:
        device_ip_address: 192.168.1.202
        udp_port: 2378
        ptc_port: 9347
        use_ptc_connected: true #false
        host_ip_address: ""
        correction_file_path: "/home/hello-robot/stretch_user/stretch-yyy-xxxx/calibration_hesais/left_lidar_calibration.dat"
      
      # Public module settings go back outside
      use_timestamp_type: 0
      fov_start: -1
      fov_end:  -1
      
    ros:
      ros_frame_id: lidar_left_link                      
      ros_send_packet_topic: /lidar_packets_left         
      ros_send_point_cloud_topic: /lidar_points_left     
      ros_send_imu_topic: /lidar_imu_left     
      ros_send_ptp_topic: /lidar_ptp_left           
      send_packet_ros: false                             
      send_point_cloud_ros: true 
      send_imu_ros: true                           

  - driver:
      use_gpu: false
      source_type: 1
      
      lidar_udp_type:
        device_ip_address: 192.168.1.201
        udp_port: 2368
        ptc_port: 9347
        use_ptc_connected: true #false
        host_ip_address: ""
        correction_file_path: "/home/hello-robot/stretch_user/stretch-yyy-xxxx/calibration_hesais/right_lidar_calibration.dat"
      
      use_timestamp_type: 0
      fov_start: -1
      fov_end:  -1
      
    ros:
      ros_frame_id: lidar_right_link                      
      ros_send_packet_topic: /lidar_packets_right         
      ros_send_point_cloud_topic: /lidar_points_right     
      ros_send_imu_topic: /lidar_imu_right   
      ros_send_ptp_topic: /lidar_ptp_right             
      send_packet_ros: false                              
      send_point_cloud_ros: true
      send_imu_ros: true   