"""
Uses the C++ Depth AI nodes to publish camera streams.
By default, the images are rotated because the cameras are mounted sideways. This node does not correct this.

This launch file also publishes the camera_info topic. It expects a Luxonis calibration yaml file at
- /home/user/stretch_user/stretch-se4-0000/calibration_ros_camera_info_left.yaml
- /home/user/stretch_user/stretch-se4-0000/calibration_ros_camera_info_right.yaml
- /home/user/stretch_user/stretch-se4-0000/calibration_ros_camera_info_center.yaml

At the time of writing, the calibration file is generated by stretch_robosense,
which outputs a file that matches the format the Luxonis API expected, like this:

```
image_width: 1920
image_height: 1200
camera_name: /left # or /right
camera_matrix:
  rows: 3
  cols: 3
  data: [800.40414,   0.     , 638.37063,
           0.     , 799.68286, 360.37479,
           0.     ,   0.     ,   1.     ]
distortion_model: equidistant #aka fisheye
distortion_coefficients:
  rows: 1
  cols: 4
  data: [0.107416, -0.285425, -0.005807, -0.001530]
rectification_matrix:
  rows: 3
  cols: 3
  data: [ 0.,0.,0.,
          0.,0.,0.,
         0.,0.,0.]
projection_matrix:
  rows: 3
  cols: 4
  data: [833.04045,   0.     , 616.04111,   0.     ,
           0.     , 833.04045, 359.7206 ,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]

```


At the time of writing, there are no Jazzy pre-built luxonis depthai_ros_driver for their V3 api. Therefore, for the best performance, we build the kilted depthai_core from source. This was recommended directly by Luxonis:

```
cd ~/ament_ws/src
git clone -b kilted https://github.com/luxonis/depthai-ros.git
git clone -b kilted https://github.com/luxonis/depthai-core.git
cd depthai-core
git submodule update --init --recursive

cd ~/ament_ws
rosdep install --from-paths src --ignore-src  -y
export MAKEFLAGS="-j 4" # the NUC cannot handle the memory intensive build of depthai_core, this is the best config for getting a successful build.
colcon build --executor sequential
```
"""

import os
from pathlib import Path

from ament_index_python import get_package_share_directory
from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, OpaqueFunction
from launch.conditions import IfCondition
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import ComposableNodeContainer, Node
from launch_ros.descriptions import ComposableNode
from stretch4_body.subsystem.cameras.adapters.luxonis_camera_adapter import (
    get_device_port_by_product_name,
)
from stretch_core.vision.vision_topics import (
    VisionTopics,
    get_camera_calibration_file_path,
)


def is_launch_config_true(context, name):
    return LaunchConfiguration(name).perform(context) == "true"


def generate_launch_description():
    use_rviz_arg = DeclareLaunchArgument(
        "use_rviz",
        default_value="false",
        description="If true, launch Rviz2 automatically.",
    )

    use_left = DeclareLaunchArgument(
        "use_left",
        default_value="true",
    )
    use_right = DeclareLaunchArgument(
        "use_right",
        default_value="true",
    )
    use_center = DeclareLaunchArgument(
        "use_center",
        default_value="false",
    )

    launch_args = [
        use_rviz_arg,
        use_left,
        use_right,
        use_center,
    ]

    return LaunchDescription(launch_args + [OpaqueFunction(function=launch_setup)])


def launch_setup(context, *args, **kwargs):

    is_use_center = is_launch_config_true(context, "use_center")

    # The ribbon cables are swapped in the head, so left is right and right is left. There is a ros2 remapping on the topics below too.
    is_use_right = is_launch_config_true(context, "use_left")
    is_use_left = is_launch_config_true(context, "use_right")

    def get_pipeline_type():
        if is_use_center and (is_use_left or is_use_right):
            return "RGBStereo"
        elif is_use_center and not (is_use_left or is_use_right):
            return "RGB"
        elif is_use_left or is_use_right:
            return "Stereo"

        raise Exception("On of use_left, use_right, or use_center must be true.")

    left_right_camera_fps = 15.0 if is_use_center else 30.0
    params = {
        # Parameters should match keys in ~/ament_ws/src/depthai-ros/depthai_ros_driver/include/depthai_ros_driver/param_handlers/base_param_handler.hpp
        "pipeline_gen": {
            "i_pipeline_type": get_pipeline_type(),
            "i_nn_type": "none",
            "i_enable_imu": False,
            "i_enable_rgbd": False,
        },
        "driver":{
                # This stops the driver from confusing the OAK-D FFC-3 board in the head with the SR gripper camera.
                "i_usb_port_id": get_device_port_by_product_name("OAK-FFC-3P")
        },
        "rgb": {
            "i_calibration_file": f"file://{get_camera_calibration_file_path("center")}",
            "i_resolution": "12MP",
            "i_width": 4056,
            "i_height": 3040,
            "i_max_q_size": 2,
            "i_fps": 5.0,
            "i_publish_topic": is_use_center,
            "i_publish_compressed": False,
            "i_publish_raw": is_use_center,
            "i_enable_lazy_publisher": True,  # enables/disables publishing based on the number of subscribers present
            "i_undistorted": False,
            # "i_tf_parent_frame": "camera_center_optical_link", # These are getting ignored... hack below
            # "i_tf_base_frame": "camera_center_optical_link",
        },
        "left": {
            "i_board_socket_id": 1,
            "i_calibration_file": f"file://{get_camera_calibration_file_path("left")}",
            "i_width": 1920,
            "i_height": 1200,
            "i_max_q_size": 2,
            "i_fps": left_right_camera_fps,
            "i_publish_topic": is_use_left,
            "i_publish_compressed": False,
            "i_publish_raw": is_use_left,
            "i_enable_lazy_publisher": True,  # enables/disables publishing based on the number of subscribers present
            "i_undistorted": False,
            # "i_tf_parent_frame": "camera_left_optical_link", # These are getting ignored... hack below
            # "i_tf_base_frame": "camera_left_optical_link",
        },
        "right": {
            "i_board_socket_id": 2,
            "i_calibration_file": f"file://{get_camera_calibration_file_path("right")}",
            "i_width": 1920,
            "i_height": 1200,
            "i_max_q_size": 2,
            "i_fps": left_right_camera_fps,
            "i_publish_topic": is_use_right,
            "i_publish_compressed": False,
            "i_publish_raw": is_use_right,
            "i_enable_lazy_publisher": True,  # enables/disables publishing based on the number of subscribers present
            "i_undistorted": False,
            # "i_tf_parent_frame": "camera_right_optical_link", # These are getting ignored... hack below
            # "i_tf_base_frame": "camera_right_optical_link",
        },
    }

    print(f"Luxonis Launch Params = {params}")

    camera_names=  ["left", "right", "center"]
    
    def get_driver_name(camera_name):
        return "rgb" if camera_name == "center" else camera_name

    def create_remappings(camera_name:str):
        driver_name = get_driver_name(camera_name)
        if driver_name == camera_name:
            return []
            
        return [
        (
            VisionTopics.image_raw(driver_name),
            VisionTopics.image_raw(camera_name),
        ),
        (
            VisionTopics.compressed(driver_name),
            VisionTopics.compressed(camera_name),
        ),
        (
            VisionTopics.compressed_depth(driver_name),
            VisionTopics.compressed_depth(camera_name),
        ),
        (
            VisionTopics.zstd(driver_name),
            VisionTopics.zstd(camera_name),
        ),
        (
            VisionTopics.theora(driver_name),
            VisionTopics.theora(camera_name),
        )
    ]

    luxonis_node_remappings = []
    for camera_name in camera_names:
        luxonis_node_remappings += create_remappings(camera_name)

    # At the time of writing this, the Luxonis DepthAI Driver does not publish the correct camera_info topic.
    camera_info_nodes = []
    for camera_name in ["left", "right", "center"]:
        calibration_file_path = get_camera_calibration_file_path(camera_name)
        if is_launch_config_true(context, f"use_{camera_name}") and Path(calibration_file_path).exists():
            camera_info_nodes.append(
                Node(
                    package="stretch_core",
                    executable="camera_info_publisher",
                    name=f"camera_info_publisher_{camera_name}",
                    parameters=[
                        {
                            "camera_name": camera_name,
                        }
                    ],
                )
            )
            luxonis_node_remappings.append(
                (
                    VisionTopics.camera_info(get_driver_name(camera_name)),
                    VisionTopics.camera_info_luxonis(camera_name),
                ),
            )
        else:
            print(f"{camera_name} does not have a calibration file at {calibration_file_path}. Publishing the Luxonis default camera_info topic.")
            luxonis_node_remappings.append(
                (
                    VisionTopics.camera_info(get_driver_name(camera_name)),
                    VisionTopics.camera_info(camera_name),
                ),
            )


    camera_node = ComposableNodeContainer(
        name=f"luxonis_container",
        namespace="",
        package="rclcpp_components",
        executable="component_container",
        composable_node_descriptions=[
            ComposableNode(
                package="depthai_ros_driver",
                plugin="depthai_ros_driver::Driver",
                name=VisionTopics.cameras_namespace()[1:],
                namespace="",
                parameters=[
                    params,
                ],
                # This is a remapping of the topics published by the node.
                # This also remaps luxonis's rgb topic to our center topic.
                # Lastly, these topic are published with the Luxonis config params in this file; changing these params may yield different topics that could break this remapping.
                remappings=luxonis_node_remappings
            )
        ],
        output="both",
    )

    # The driver ignores i_tf_base_frame, so as a hack, we publish a static transform to connect the driver frame to the optical link.
    static_tf_nodes = []
    for camera_name in camera_names:
        if is_launch_config_true(context, f"use_{camera_name}"):
            driver_name = get_driver_name(camera_name)
            static_tf_nodes.append(
                Node(
                    package="tf2_ros",
                    executable="static_transform_publisher",
                    name=f"static_tf_{camera_name}_camera",
                    arguments=[
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        f"camera_{camera_name}_optical_link",
                        f"{VisionTopics.cameras_namespace()}_{driver_name}_camera_optical_frame",  # This is the name published by the driver
                    ],
                )
            )

    rviz_config_path = os.path.join(
        get_package_share_directory("stretch_core"), "rviz", "cameras.rviz"
    )

    rviz_node = Node(
        package="rviz2",
        executable="rviz2",
        name="rviz2",
        output="screen",
        arguments=["-d", rviz_config_path],
        condition=IfCondition(LaunchConfiguration("use_rviz")),
    )

    return [camera_node, rviz_node] + camera_info_nodes + static_tf_nodes