[develop]
script_dir=$base/lib/stretch_kinematics

[install]
install_scripts=$base/lib/stretch_kinematics

[options.entry_points]
console_scripts =
    velocity_limiter = stretch_kinematics.nodes.velocity_limiter:main
    task_space_controller = stretch_kinematics.nodes.task_space_controller:main

[flake8]
max-line-length = 99
extend-ignore = E203, W503

[pep257]
ignore = D203,D212,D404,D406,D407,D412,D413
