services:
  stretch-simulation: 
    image: stretch-simulation:latest
    container_name: stretch4-sim-container
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    network_mode: host
    stdin_open: true
    tty: true
    shm_size: '2gb'
    environment: 
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      # X11 socket for GUI
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${HOME}/.Xauthority:/root/.Xauthority:rw
      # Mount local source code for development
      # - ./:/root/ament_ws/src/stretch4_ros2/stretch_simulation:rw
      #- ~/Projects/stretch_4/stretch4_ros2/:/root/ament_ws/src/stretch4_ros2:rw
      #- ~/Projects/stretch_4/stretch4_mujoco:/root/repos/stretch4_mujoco/:rw
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command:
      - bash
      - -c
      - |  
        terminator -u --title="Stretch 4 MuJoCo"

        